# Generated by Django 5.0.6 on 2026-04-24 13:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionOption",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("option_text", models.CharField(max_length=500)),
                (
                    "option_value",
                    models.CharField(
                        help_text="Stored answer code, e.g. 'employed_private'", max_length=100
                    ),
                ),
                ("display_order", models.IntegerField(db_index=True, default=0)),
                (
                    "is_other",
                    models.BooleanField(
                        default=False,
                        help_text="If True, renders an open text input alongside this option",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional image for visual choice questions",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "score_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Used for scored assessments or quizzes",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="surveys.question",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.AddConstraint(
            model_name="questionoption",
            constraint=models.UniqueConstraint(
                fields=("question", "option_value"), name="unique_option_value_per_question"
            ),
        ),
    ]
