# Generated by Django 5.0.6 on 2026-04-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0002_questionoption_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="scheduled_publish_at",
            field=models.DateTimeField(
                blank=True, help_text="Schedule automatic publishing at this time", null=True
            ),
        ),
    ]
