# Generated by Django 5.0.6 on 2026-04-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0003_survey_scheduled_publish_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="scheduled_closed_at",
            field=models.DateTimeField(
                blank=True, help_text="Schedule automatic closing at this time", null=True
            ),
        ),
    ]
