# Generated by Django 5.0.6 on 2026-04-26 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0002_seed_beat_schedules"),
        ("surveys", "0004_survey_scheduled_closed_at"),
    ]

    operations = []
